### ISSUE TITLE
Preserve state upon uncaught exception

### ISSUE THREAD

**Issue by bwoebi** [krakjoe/phpdbg#112]
This will need a search through the stack to check if there's some catch instruction which matches the thrown exception. If there's none and no global exception handler, then halt execution and offer phpdbg prompt. (But still offer a method to continue in case there are some finally blocks / shutdown handler so that users can cleanly shutdown)

**Comment by joshua-paddle** [comment]
I second this, with the additional note that it would be really really useful to have the ability to dump the current state on command.

As an example use case, my web application catches all exceptions so that it can write them to a log file and deliver an appropriate error message to the user. I would love to be able to not just record the exception and stack trace to the log, but the entire process state, so that I can download it later to open up in phpdbg and step through it manually, with all debugging tools available - e.g. things like getting variable values in the caller's scope.

**Comment by bwoebi** [comment]
You mean something like core dumps, just for PHP space?

That'd be really complicated… It's not so hard with gdb which just can copy the stack and then virtual memory space each all at once… But for PHP? hmmm… It's on the border to the impossible.

**Comment by joshua-paddle** [comment]
That woudl be incredibly useful, but I can see how it would also be incredibly difficult. However, couldn't you dump the state of the entire php process, as a gdb-style core dump, and then open that back up later? Then you'd have a lot of extra information you don't need, but it would preserve all the php-space stuff as well. No idea if this is possible or just some crazy idea, but in general the more memory dumping options available, the better.

**Comment by bwoebi** [comment]
That's what a php-src core dev can do… dump the process and then inspect it via gdb. It'd be interesting if we could somehow make core dumps continue execution and import into phpdbg control. But I currently have no idea about what kernel APIs etc. exist for that or how that'd work… A quick google search wasn't very successful :-(

**Comment by bwoebi** [comment]
Implemented in php 7 source tree.
