### ISSUE TITLE
Allow call of dbg directly from abritrary line in some PHP script

### ISSUE THREAD

**Issue by vincent-ferotin** [krakjoe/phpdbg#132]
Hi, DBG developers.

It would be great to allow direct invocation of *dbg* from a given line in PHP script, such as, when the interpreter encounters it, the debugger is loaded and waiting for command at this new"breakpoint".

This is a feature available for example in Python [pdb](https://docs.python.org/2/library/pdb.html) through "magic" ```import pdb; pdb.set_trace()``` insertion ([doc](https://docs.python.org/2/library/pdb.html#pdb.set_trace)). Such feature is also implemented by [Psysh](http://psysh.org/) with its ```eval(\Psy\sh());``` ([doc](http://psysh.org/#features)).

Such feature would allow direct debugging regardless of actual binary invoked to run current script, and could be useful for example when unittesting (e.g. where binary is ```phpunit```). I suppose there could be other relevant scenarios ;-)

Thank you for taking this suggestion in account (whether it will exist or not)!

**Comment by bwoebi** [comment]
There is a function called `phpdbg_break()` … When you run that via `phpdbg -r your_script.php`, it will halt phpdbg and enter interactive mode upon breakpoint.

**Comment by vincent-ferotin** [comment]
Well, I was probably not clear enough: all the purpose of that ticket is to ask for call of phpdbg interface *without* calling script to debug directly through `phpdbg` binary via command-line shell. What I'd like is to be able to insert some sort of `phpdbg_break();` PHP code, and at execution get the phpdbg interface.

When for example you'd like to open [Psysh](http://psysh.org/) REPL in a given point of some of your script, you insert a `eval(\Psy\sh());` at the desired line. And *regardless of the binary interpreting this script*, which could be `php` it-self, `phpunit`, and so on (perhaps `phpdbg` but I've never tried it), Psysh REPL interface opens and lets you e.g. examine current defined variables. Please test this example with Psysh (see [its documented usage](http://psysh.org/#usage)) if my explanation is not sufficient (and I perfectly understand it could be ^^;).

To take a concrete and complete example of this need, let imagine you have an application composed of multiple files, dispatched on your project's directory tree. To simplify, the project at this stage is only composed on 1) database models, 2) unit tests (via [PHPUnit](https://phpunit.de/)) on these models. The models stand on `src/Models/` directory, whereas tests are on `tests/Models/`, following this tree (matching [PSR-4](http://www.php-fig.org/psr/psr-4/) recommendation):
```
- src/  # namespace = example\Library
   \- Models/
      \- Book.php
      \- BookCollection.php 
- tests/  # namespace = example\Library\Tests
   \- Models/
      \- BookTest.php  # tests for Models\Book
      \- BookCollectionTest.php  # tests for Models\BookCollection
```
(Class autoloading could be achieved thanks e.g. [Composer autoloader](https://getcomposer.org/doc/04-schema.md#autoload), that PHPUnit is aware of.)
When running unit test suite, one of your test failed, and you'd want to examine living code just before failing occurs. Failling occurs for example in  `example\Library\Tests\Models\BookTest::testRegister` method, and more specifically in `example\Library\Models\Book::register` method. This is inside this latest piece of code you'd like starting debugging, so where you'll insert the [future magic `phpdbg_break();` call], for examining current variables and run code step by step. So script to actually debug is `src/Models/Book.php`, but in a context where it is "called" by `tests/Models/BookTest.php`, it-self called by `phpunit`.

So in this example I suppose quite common:
 * PHP runner is `phpunit`, *not phpdbg*;
 * script to debug is not an alone-and-autosufficient piece of code;
 * debugging occurs in a given context (to examine and walk through), provided by a 3rd-party and other part of the project (code to debug is not necessarily directly callable as-is by a PHP interpreter).

I hope to be clear, or at least complete, but please do not hesitate to comment / ask / correct / etc. :-)

**Comment by bwoebi** [comment]
Basically context takeover and launching phpdbg?

Yeah, that's not really possible I fear. When you have the example of Psysh, you have all in one binary...
It's like you'd have a python binary and then would try to call psysh from it. Does that work? I don't believe so. Same issue here.

Sorry, but that's asking for the nearly impossible ;-)

**Comment by vincent-ferotin** [comment]
> Basically context takeover and launching phpdbg?

Yes, that's it!

> When you have the example of Psysh, you have all in one binary

I'm sorry to not be sure to understand what you mean. With the example of Psysh `eval(\Psy\sh());`, actually my binary is `phpunit`. (If I misunderstood, could you please reformulate ?-)

Perhaps this works for Psysh because it's written in PHP, and so is callable by any PHP interpreter?
And if I'll infer from what you described be, perhaps it is not (at current time) possible with phpdbg because it is written in C (with additional constraints I'll refer to hereafter)?
If this hypothesis is right, then I've already found a [previous reference](http://www.reddit.com/r/PHP/comments/1vige3/anybody_use_phpdbg_as_their_debugger_how_does_it/cesp4sk) of (someone else asking tor a similar feature, and hearing quite) the same position as yours. 

At this point (and assuming above points are not wrong, of course) I'd like to know what other users and developers think about such "request for enhancement". **Is it a desirable feature for the users, and then for the project and its goals?** Also I'm interested in *your* opinion, from a person who took some time to answer me -- thank you! So, what is the publicity to this current ticket, i.e. are some other people aware of its existence? Does the project have a mailing-list (I've only found a chat on stackoverflow -- and I'm afraid to not be enough fluent and speed to take part of it)?

Then, if such feature is desirable, we could search for feasible paths to implementation, and estimate if it's worth the cost. Again, assuming above points are not wrong, my very first and simple guess would be that a possible path could be:
1. make phpdbg a library, to allow be callable by other softwares;
2. offer a PHP API to this lib.
I could perfectly figure out that these steps are *big*... that's the main reason of previous paragraph on project's goals and users' needs, and request for other opinions.

As far as I understand (and please correct me if/where I'm wrong: I currently do not use phpdbg (yet)), language in which the tool is written (C) is not an obstacle *in essence* to be callable directly from PHP code. I think that main limitation comes from the idea of how phpdbg should be used. It was designed to only be callable through command-line. Because it was though to debug *scripts*, that is an auto-sufficient piece of PHP code. But perhaps it should be desirable that, in some point on its future road, it will allow debugging *applications*, that is a set of interdependent scripts?

**Comment by bwoebi** [comment]
As said, psych runs directly in PHP scope. it unpacks itself inside PHP and then starts the console (or, if available, forks first). … But ultimately it's directly intercepting the running script here.
Also, all it has access to, is current stack frame and its variables… nothing else.

But to truly intercept the PHP core, you need to write it in C. Let's assume we could get control of it via an extension. We'd have to install us immediately into core, because we can't change that later on (we can't manually go and change the function called on the stack… that won't work. At least not with C. (If it all were assembly, maybe…, but that's obviously not an option because portability.))

The official mailing list of the project is basically PHP-internals (It is part of the PHP distribution currently, so…)
That chat on stackoverflow is where I and some other people from internals hang around (not only us, also others), and sometimes discuss internals things, RFCs etc. … Some smart people in there ;-)

Generally, I'd personally *like* to have such a feature, but I doubt it's feasibility. 

There's one reason why this is a SAPI. Because we need to be able to interact with the user from the very beginning on … and we need to initialize *before* any other core component loads in. E.g. we overwrite the zend memory managers handlers, which strictly needs to happen before anything is allocated with them. [E.g. watchpoints heavily rely on that.] Also, we have some possibilities to e.g. interrupt a running program with two consecutive sigint signals, to inspect environment safely (e.g. if some internal call blocks, but you have no idea where), which needs a specially sandboxed environment to not crash it. … which is ultimately realized by a sigsegv handler, to do a longjump abort to a safe place in case we tried an invalid read. Which needs to be wrapped in a try/catch handler in the main fucntion (for Windows).

So, it has as well design reasons (like you mention), but also technical reasons, which is why it must be that way.
For the basic features in a lib… yeah, there's xdebug which can do it reasonably well. But it is also restricted in some parts… hence it doesn't support for example watchpoints.

I'd really wish to see something like that, but I'm not sure whether we can do that. gdb for example can intercept a process and execute under its own control. with PHP stack, I'm not sure if it's possible.

**Comment by vincent-ferotin** [comment]
Thanks a lot for this detailed answer! It is sad that it would be too difficult to implement.
So, as I don't know project's politics regard this type of ticket, I let you choose its future...

**Comment by bwoebi** [comment]
@vincent-ferotin It's just my view on it… I would be more than happy to see someone proving me wrong :-)

Closing this issue for now.
