### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by yuloh** [krakjoe/phpdbg#159]
Hello,

I'm experiencing the same issue as #154.

Using @theofidry's branch (after making [these fixes](https://github.com/yuloh/phpdbg-bug-demo/tree/fix-test) to get coverage to generate) I run into the memory issue.

I tried simplifying the test case [and removing all prophecy calls](https://gist.github.com/yuloh/60add4dda468aa952f604610d3176342).  After that the memory issue goes away, so it seems to be linked to prophecy.

In my case I am not using prophecy at all.  My tests that have this issue are using doctrine, so I'm currently trying to figure out what prophecy and doctrine have in common that could be causing this.

Both projects are using doctrine/instantiator but I can't reproduce the issue using doctrine/instantiator alone.

I'm working on trying to figure out the simplest test case that has this issue.  At the moment I'm not really sure what part of these 2 libraries is causing it.

**Comment by yuloh** [comment]
Oddly enough, if I run the test with `memory_limit` set to `-1`, phpdbg will stall indefinitely using around 200mb of memory.  It never reaches 1GB like it will with a memory limit set.

When I kill the process it's stuck here:

```
[Current opline: 0x104fa6a00 (op #3) in /<my code folder>/phpdbg-bug-demo/vendor/sebastian/recursion-context/src/Context.php:129]
>00129:             if (isset($array[$hash]) && $array[$hash] === $hash) {
 00130:                 unset($this->arrays[$key][$hash]);
 00131:
```

**Comment by bwoebi** [comment]
There seems to be a problem with __call() magic handling.
I'm looking into it.

It's not a memory leak, it's an infinite loop. The "leaked" memory is the executed opcodes log. (which obviously grows as more and more opcodes are being executed.)

**Comment by bwoebi** [comment]
I think I see what's going on.

Internal state of the phpdbg driver is being compared (as being part of an Exception objects stack trace)... And that is bad. There are multiple arrays of sizes like 575, 565, 538, whose elements are all each (empty) arrays! … In total it's a 5504 empty arrays (of which 98% are inside SebastianBergmann\CodeCoverage\CodeCoverage->data - which is coverage data).

SebastianBergmann\Exporter\Exporter::recursiveExport() is calling SebastianBergmann\RecursionContext::containsArray() for each array entry which contains another array and then adds this array to the list of arrays to search next time.
That's O(n^2).

Thus, there's like 11 opcodes being executed n*(n-1)/2 times upon each call of containsArray. Good luck when your array contains multiple hundreds of (in this case: empty) arrays.

Just to illustrate: 5504*5503/2*11 = 166.586.816 … So … it executes more than a hundred million opcodes…

That's a ridiculous amount of executed opcodes … and … during code coverage each executed opcode is stored, taking 48 bytes.
You see that the memory usage goes through the ceiling there… taking about 8 GB of opcode data alone. And not to forget it will just take eternally to execute all these opcodes. 

And then note that there are two of these… (expected + actual) … so, multiply this…

I've tried to run it… After 28 GB RAM used, I've eventually decided to stop it...

But in general - the issue is phpunit's RecursionContext doing O(n^2) operations on arbitrary user data.

**Comment by yuloh** [comment]
Wow, that's pretty crazy.  Thanks for the detective work 😀

**Comment by yuloh** [comment]
Just to clarify, is it actually an infinite loop because the call generates more opcodes, or is it slow enough it can't keep up?

**Comment by bwoebi** [comment]
@yuloh the latter.
